#Confluent CP 5.3.1 docker images
#Kafka Topics UI 0.9.4
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1 
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_DATA_DIR: /tmp/zookeeper
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - /home/zookeeper-data:/tmp/zookeeper
  kafka:
    image: confluentinc/cp-kafka:5.3.1 
    depends_on:
      - zookeeper
    ports:
      - 9092:9092                 # Outside access to Kafka Broker
      - 9091:9091                 # Internal access to Kafka Broker
      - 2181:2181                 # Zookeeper
      - 9581-9585:9581-9585       # JMX Ports
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_LISTENERS: INTERNAL://:9091,EXTERNAL://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9091,EXTERNAL://<PIBLIC_IP_ADDRESS>:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /tmp/kafka-logs
    volumes:
      - /home/kafka-data:/tmp/kafka-logs
  kafka-rest-proxy:
    image: confluentinc/cp-kafka-rest:5.3.1 
    hostname: kafka-rest-proxy
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082/
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://kafka-schema-registry:8081/
      KAFKA_REST_HOST_NAME: kafka-rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: INTERNAL://kafka:9091
    depends_on:
      - zookeeper
      - kafka
  kafka-topics-ui:
    image: landoop/kafka-topics-ui:0.9.4
    hostname: kafka-topics-ui
    ports:
      - "3030:3030"
    environment:
      KAFKA_REST_PROXY_URL: "http://kafka-rest-proxy:8082/"
      PROXY: "true"
    depends_on:
      - zookeeper
      - kafka
      - kafka-rest-proxy
